### PR TITLE
see ipfs.ts

### PR DESCRIPTION
**Pull request by 1cbyc**
used "try...catch" block to handle potential errors and log them to the console for debugging. 

adjusted the import functions too.

hope the changes look good?

### CODE REVIEW

**Comment by SgtPooki** [comment]
@1cbycthanks for the contribution but we should not be using require statements anymore

**Comment by 1cbyc** [comment]
> @1cbycthanks for the contribution but we should not be using require statements anymore

ooh, okay. that makes sense.

**Review by SgtPooki — CHANGES_REQUESTED** [review]
I dont see the benefits of these changes, but do see a regression in maintainable code.

It would be easier to get a significantly smaller change merged that doesnt change code style or patterns.

**Review by achingbrain — CHANGES_REQUESTED** [review]
@1cbyc thank you for taking the time to open this PR.

Could you go into a bit of detail about why these changes are necessary and what problem they solve?

**Comment by achingbrain** [comment]
I'm going to close this PR, it's not clear what value the changes add and it won't run due to use of CJS in ESM.

**Pull request closed without merging**
