### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by achingbrain**
:robot: I have created a release *beep* *boop*
---

<details><summary>bitswap: 1.0.0</summary>

### Features

* add @helia/bitswap with sessions ([#409](https://github.com/ipfs/helia/issues/409)) ([e582c63](https://github.com/ipfs/helia/commit/e582c63ca296c789312f5fcf5e3e18f267f74c03))

### Bug Fixes

* improve sessions implementation ([#495](https://github.com/ipfs/helia/issues/495)) ([9ea934e](https://github.com/ipfs/helia/commit/9ea934ed7208e87c28bc65e9090bdedf66ceeffd))
* increase default listers on abort signals ([#484](https://github.com/ipfs/helia/issues/484)) ([7cd012a](https://github.com/ipfs/helia/commit/7cd012aa2ba568845d49d63a71806d20f6ac678f))
* remove wants from wantlist when multiple block retrievers are used ([#491](https://github.com/ipfs/helia/issues/491)) ([b1c761d](https://github.com/ipfs/helia/commit/b1c761db6db7a7aca3044263fdd5e8967204deeb))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.0.0 to ^4.2.0
    * @helia/utils bumped from ^0.1.0 to ^0.2.0
</details>

<details><summary>block-brokers: 2.1.0</summary>

### Features

* add @helia/bitswap with sessions ([#409](https://github.com/ipfs/helia/issues/409)) ([e582c63](https://github.com/ipfs/helia/commit/e582c63ca296c789312f5fcf5e3e18f267f74c03))
* add block session support to @helia/interface ([#398](https://github.com/ipfs/helia/issues/398)) ([5cf216b](https://github.com/ipfs/helia/commit/5cf216baa6806cd82f8fcddd1f024ef6a506f667))
* add sessions to trustless gateways ([#459](https://github.com/ipfs/helia/issues/459)) ([6ddefb0](https://github.com/ipfs/helia/commit/6ddefb01154b970f5ab7ec7cb7445d9eedbc5474))

### Bug Fixes

* improve sessions implementation ([#495](https://github.com/ipfs/helia/issues/495)) ([9ea934e](https://github.com/ipfs/helia/commit/9ea934ed7208e87c28bc65e9090bdedf66ceeffd))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/bitswap bumped from ^0.0.0 to ^1.0.0
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
    * @helia/utils bumped from ^0.1.0 to ^0.2.0
</details>

<details><summary>car: 3.1.3</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
  * devDependencies
    * @helia/unixfs bumped from ^3.0.3 to ^3.0.4
</details>

<details><summary>dag-cbor: 3.0.3</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
</details>

<details><summary>dag-json: 3.0.3</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
</details>

<details><summary>http: 1.0.4</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/block-brokers bumped from ^2.0.3 to ^2.1.0
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
    * @helia/routers bumped from ^1.0.2 to ^1.0.3
    * @helia/utils bumped from ^0.1.0 to ^0.2.0
</details>

<details><summary>interface: 4.2.0</summary>

### Features

* add block session support to @helia/interface ([#398](https://github.com/ipfs/helia/issues/398)) ([5cf216b](https://github.com/ipfs/helia/commit/5cf216baa6806cd82f8fcddd1f024ef6a506f667))

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))
* improve sessions implementation ([#495](https://github.com/ipfs/helia/issues/495)) ([9ea934e](https://github.com/ipfs/helia/commit/9ea934ed7208e87c28bc65e9090bdedf66ceeffd))
</details>

<details><summary>interop: 6.1.0</summary>

### Features

* add @helia/bitswap with sessions ([#409](https://github.com/ipfs/helia/issues/409)) ([e582c63](https://github.com/ipfs/helia/commit/e582c63ca296c789312f5fcf5e3e18f267f74c03))

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/block-brokers bumped from ^2.0.3 to ^2.1.0
    * @helia/car bumped from ^3.1.2 to ^3.1.3
    * @helia/dag-cbor bumped from ^3.0.2 to ^3.0.3
    * @helia/dag-json bumped from ^3.0.2 to ^3.0.3
    * @helia/http bumped from ^1.0.3 to ^1.0.4
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
    * @helia/ipns bumped from ^7.2.0 to ^7.2.1
    * @helia/json bumped from ^3.0.2 to ^3.0.3
    * @helia/mfs bumped from ^3.0.3 to ^3.0.4
    * @helia/routers bumped from ^1.0.2 to ^1.0.3
    * @helia/strings bumped from ^3.0.2 to ^3.0.3
    * @helia/unixfs bumped from ^3.0.3 to ^3.0.4
    * helia bumped from ^4.1.0 to ^4.1.1
</details>

<details><summary>ipns: 7.2.1</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
</details>

<details><summary>json: 3.0.3</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
</details>

<details><summary>mfs: 3.0.4</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/unixfs bumped from ^3.0.3 to ^3.0.4
</details>

<details><summary>routers: 1.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
</details>

<details><summary>strings: 3.0.3</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
</details>

<details><summary>unixfs: 3.0.4</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
</details>

<details><summary>utils: 0.2.0</summary>

### Features

* add block session support to @helia/interface ([#398](https://github.com/ipfs/helia/issues/398)) ([5cf216b](https://github.com/ipfs/helia/commit/5cf216baa6806cd82f8fcddd1f024ef6a506f667))

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))
* blockstore operations should throw when passed an aborted signal ([#497](https://github.com/ipfs/helia/issues/497)) ([9a10498](https://github.com/ipfs/helia/commit/9a10498e55b4380191135535f7f607082e9c00c6))
* cancel in-flight block requests when racing brokers ([#490](https://github.com/ipfs/helia/issues/490)) ([395cd9e](https://github.com/ipfs/helia/commit/395cd9e6ac2f829ef47b503cc7a6c77922f484cf))
* improve sessions implementation ([#495](https://github.com/ipfs/helia/issues/495)) ([9ea934e](https://github.com/ipfs/helia/commit/9ea934ed7208e87c28bc65e9090bdedf66ceeffd))
* increase default listers on abort signals ([#484](https://github.com/ipfs/helia/issues/484)) ([7cd012a](https://github.com/ipfs/helia/commit/7cd012aa2ba568845d49d63a71806d20f6ac678f))
* wrap blockstore in identity blockstore ([#493](https://github.com/ipfs/helia/issues/493)) ([b67ac5f](https://github.com/ipfs/helia/commit/b67ac5f16eca1df5534c985045250bdb334a85cf))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
</details>

<details><summary>helia: 4.1.1</summary>

### Bug Fixes

* add sideEffects: false to package.json ([#485](https://github.com/ipfs/helia/issues/485)) ([8c45267](https://github.com/ipfs/helia/commit/8c45267a474ab10b2faadfebdab33cfe446e8c03))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @helia/block-brokers bumped from ^2.0.3 to ^2.1.0
    * @helia/interface bumped from ^4.1.0 to ^4.2.0
    * @helia/routers bumped from ^1.0.2 to ^1.0.3
    * @helia/utils bumped from ^0.1.0 to ^0.2.0
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by SgtPooki — APPROVED** [review]

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/block-brokers-v2.1.0 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/bitswap-v1.0.0 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/car-v3.1.3 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/dag-cbor-v3.0.3 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/dag-json-v3.0.3 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/helia-v4.1.1 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/http-v1.0.4 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/interface-v4.2.0 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/interop-v6.1.0 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/ipns-v7.2.1 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/mfs-v3.0.4 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/routers-v1.0.3 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/unixfs-v3.0.4 :sunflower:

**Comment by achingbrain** [comment]
:robot: Release is at https://github.com/ipfs/helia/releases/tag/utils-v0.2.0 :sunflower:

**Pull request merged**
